[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dfr-rnn"
version = "0.0.1"
authors = [
    { name="df.roibas", email="df.roibas@gmail.com" },
]
description = "Ejemplo de como crear un paquete"
readme = "README.md"
license = { file="LICENSE.txt" }
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.urls]
"Homepage" = "https://github.com/washedfrere/dfr_rnn"
"Bug Tracker" = "https://github.com/washedfrere/dfr_rnn/issues"